# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Chris <goabonga@pm.me>

"""Repo-aware initial config generation.

Walks the working tree once and proposes a :class:`Config` populated with
one :class:`Component` per detected manifest. Component names come from the
manifest itself (``[project].name`` in ``pyproject.toml``, ``[package].name``
in ``Cargo.toml``, the last segment of ``module …`` in ``go.mod``, ``name``
in ``Chart.yaml`` and ``package.json``, etc.).

Recognised manifests (all searched recursively, except where noted):

* Python - ``pyproject.toml`` at repo root
* Helm - every ``Chart.yaml``
* Rust - every ``Cargo.toml`` (workspaces with ``[workspace.package].version``
  collapse to a single component; member crates that inherit are skipped)
* Go - every ``go.mod`` (tag-driven, no version file)
* Gradle - root ``gradle.properties`` with a ``version=`` line
* Node.js - ``package.json`` at repo root, with workspace members expanded
  when the root declares ``workspaces`` (or a sibling ``pnpm-workspace.yaml``)

Common noise directories (``.git``, ``node_modules``, ``.venv``, ``target``,
``build``, ``dist``, ``vendor``, …) are excluded.

Paths only include files whose change clearly warrants a version bump:
``Dockerfile`` is included when present, but ``.dockerignore`` is not -
it almost always signals build-context hygiene rather than an artifact
change.

The discovery pipeline lives in per-ecosystem modules (:mod:`.python`,
:mod:`.cargo`, ...) plugged in via :data:`.registry.DISCOVERERS`. This
module is the orchestrator: it threads a :class:`.context.DiscoveryContext`
through every strategy, owns name-collision resolution, and runs the
post-pass relations (Python <-> Helm appVersion mirroring, Node workspace
expansion, Debian changelog detection). Stage 4 will move those relations
behind their own protocol.
"""

from __future__ import annotations

from pathlib import Path

import tomlkit

from ..config import Component, FileKey
from .context import DiscoveryContext, DiscoveryResult
from .debian import _detect_debian
from .node import _detect_node
from .registry import DISCOVERERS, DiscoveryStrategy

__all__ = [
    "DISCOVERERS",
    "DiscoveryContext",
    "DiscoveryResult",
    "DiscoveryStrategy",
    "discover_components",
    "render_config",
]


def discover_components(repo: Path) -> dict[str, Component]:
    """Return a fresh component map populated from manifests found under ``repo``."""
    context = DiscoveryContext(repo=repo)

    for discoverer in DISCOVERERS:
        for result in discoverer.discover(repo, context):
            name = context.unique(result.raw_name, result.suffix)
            context.register(name, result)

    components = context.components()

    # Post-passes (kept as free functions for now; stage 4 will move
    # them behind a RelationStrategy protocol).
    _link_python_helm_appversion(components, context)
    _detect_node(repo, components, context)
    _detect_debian(repo, components)

    return components


def _link_python_helm_appversion(
    components: dict[str, Component], context: DiscoveryContext
) -> None:
    """Mirror Python component versions onto matching Helm chart ``appVersion``.

    Single python + single chart: unambiguous, always pair. Otherwise:
    match by raw manifest name, so a 'worker' chart next to an 'api'
    python project stays independent and a multi-python repo wires each
    python to its same-named chart only.
    """
    pythons = context.by_kind("python")
    charts = context.by_kind("helm")
    if not pythons or not charts:
        return

    if len(pythons) == 1 and len(charts) == 1:
        py_name, _ = pythons[0]
        chart_name, _ = charts[0]
        py = components[py_name]
        chart_yaml_path = components[chart_name].bump_files[0].file
        py.mirrors.append(FileKey(file=chart_yaml_path, key="appVersion"))
        return

    for py_name, py_result in pythons:
        py = components[py_name]
        py_raw = py_result.raw_name
        for chart_comp_name, chart_result in charts:
            if chart_result.raw_name == py_raw:
                chart_yaml_path = components[chart_comp_name].bump_files[0].file
                py.mirrors.append(
                    FileKey(file=chart_yaml_path, key="appVersion")
                )


def render_config(
    components: dict[str, Component],
    *,
    initial_version: str = "0.1.0",
    tag_format: str = "{component}-v{version}",
) -> str:
    """Render a ``multicz.toml`` document from a component map."""
    doc = tomlkit.document()
    doc.add(tomlkit.comment("multicz.toml - generated by `multicz init`"))
    doc.add(tomlkit.comment("https://github.com/goabonga/multicz"))
    doc.add(tomlkit.nl())

    project = tomlkit.table()
    project["commit_convention"] = "conventional"
    project["tag_format"] = tag_format
    project["initial_version"] = initial_version
    doc["project"] = project

    components_root = tomlkit.table(is_super_table=True)
    for name, comp in components.items():
        section = tomlkit.table()
        section["paths"] = list(comp.paths)
        if comp.exclude_paths:
            section["exclude_paths"] = list(comp.exclude_paths)
        if comp.bump_files:
            section["bump_files"] = _filekey_array(comp.bump_files)
        if comp.mirrors:
            section["mirrors"] = _filekey_array(comp.mirrors)
        if comp.depends_on:
            section["depends_on"] = list(comp.depends_on)
        if comp.changelog is not None:
            section["changelog"] = str(comp.changelog)
        if comp.format != "default":
            section["format"] = comp.format
        if comp.debian is not None:
            debian_table = tomlkit.table()
            debian_table["changelog"] = str(comp.debian.changelog)
            debian_table["distribution"] = comp.debian.distribution
            debian_table["urgency"] = comp.debian.urgency
            debian_table["debian_revision"] = comp.debian.debian_revision
            if comp.debian.maintainer is not None:
                debian_table["maintainer"] = comp.debian.maintainer
            if comp.debian.epoch is not None:
                debian_table["epoch"] = comp.debian.epoch
            section["debian"] = debian_table
        components_root.append(name, section)
    doc.append("components", components_root)

    return tomlkit.dumps(doc)


def _inline_filekey(fk: FileKey):
    inline = tomlkit.inline_table()
    inline["file"] = str(fk.file)
    if fk.key is not None:
        inline["key"] = fk.key
    return inline


def _filekey_array(items: list[FileKey]):
    array = tomlkit.array()
    array.multiline(True)
    for fk in items:
        array.append(_inline_filekey(fk))
    return array
