# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Chris <goabonga@pm.me>

"""Repo-aware initial config generation.

Walks the working tree once and proposes a :class:`Config` populated with
one :class:`Component` per detected manifest. Component names come from the
manifest itself (``[project].name`` in ``pyproject.toml``, ``[package].name``
in ``Cargo.toml``, the last segment of ``module …`` in ``go.mod``, ``name``
in ``Chart.yaml`` and ``package.json``, etc.).

Recognised manifests (all searched recursively, except where noted):

* Python - ``pyproject.toml`` at repo root
* Helm - every ``Chart.yaml``
* Rust - every ``Cargo.toml`` (workspaces with ``[workspace.package].version``
  collapse to a single component; member crates that inherit are skipped)
* Go - every ``go.mod`` (tag-driven, no version file)
* Gradle - root ``gradle.properties`` with a ``version=`` line
* Node.js - ``package.json`` at repo root, with workspace members expanded
  when the root declares ``workspaces`` (or a sibling ``pnpm-workspace.yaml``)

Common noise directories (``.git``, ``node_modules``, ``.venv``, ``target``,
``build``, ``dist``, ``vendor``, …) are excluded.

Paths only include files whose change clearly warrants a version bump:
``Dockerfile`` is included when present, but ``.dockerignore`` is not -
it almost always signals build-context hygiene rather than an artifact
change.

The discovery pipeline lives in per-ecosystem modules (:mod:`.python`,
:mod:`.cargo`, ...) plugged in via :data:`.registry.DISCOVERERS`. This
module is the orchestrator: it threads a :class:`.context.DiscoveryContext`
through every strategy, owns name-collision resolution, and runs the
post-pass relations (Python <-> Helm appVersion mirroring, Node workspace
expansion, Debian changelog detection). Stage 4 will move those relations
behind their own protocol.
"""

from __future__ import annotations

from pathlib import Path

import tomlkit

from ..config import Component, DebianChangelogWriter, FileKey
from .context import DiscoveryContext, DiscoveryResult
from .registry import DISCOVERERS, DiscoveryStrategy
from .relations import RELATIONS, RelationStrategy, apply_relations

__all__ = [
    "DISCOVERERS",
    "RELATIONS",
    "DiscoveryContext",
    "DiscoveryResult",
    "DiscoveryStrategy",
    "RelationStrategy",
    "discover_components",
    "render_config",
]


def discover_components(
    repo: Path,
    *,
    skip: set[str] | None = None,
) -> dict[str, Component]:
    """Return a fresh component map populated from manifests found under ``repo``.

    ``skip`` filters out discovery strategies whose ``name`` matches any
    entry in the set (e.g. ``{"helm", "gradle"}`` to ignore those two
    ecosystems entirely). Relations always run — when a strategy was
    skipped its components simply aren't there and the relation no-ops.
    """
    skip = skip or set()
    context = DiscoveryContext(repo=repo)

    for discoverer in DISCOVERERS:
        if discoverer.name in skip:
            continue
        for result in discoverer.discover(repo, context):
            name = context.unique(result.raw_name, result.suffix)
            context.register(name, result)

    components = context.components()
    apply_relations(repo, components, context)
    return components


def render_config(
    components: dict[str, Component],
    *,
    initial_version: str = "0.1.0",
    tag_format: str = "{component}-v{version}",
) -> str:
    """Render a ``multicz.toml`` document from a component map."""
    doc = tomlkit.document()
    doc.add(tomlkit.comment("multicz.toml - generated by `multicz init`"))
    doc.add(tomlkit.comment("https://github.com/goabonga/multicz"))
    doc.add(tomlkit.nl())

    project = tomlkit.table()
    project["commit_convention"] = "conventional"
    project["tag_format"] = tag_format
    project["initial_version"] = initial_version
    doc["project"] = project

    components_root = tomlkit.table(is_super_table=True)
    for name, comp in components.items():
        section = tomlkit.table()
        section["paths"] = list(comp.paths)
        if comp.exclude_paths:
            section["exclude_paths"] = list(comp.exclude_paths)
        if comp.bump_files:
            section["bump_files"] = _filekey_array(comp.bump_files)
        if comp.mirrors:
            section["mirrors"] = _filekey_array(comp.mirrors)
        if comp.depends_on:
            section["depends_on"] = list(comp.depends_on)
        if comp.changelog is not None:
            section["changelog"] = str(comp.changelog)
        if comp.writers:
            writers_array = tomlkit.aot()
            for writer in comp.writers:
                table = tomlkit.table()
                table["type"] = writer.type
                table["file"] = str(writer.file)
                # Only emit non-default per-writer fields, mirroring how
                # `_filekey_array` only emits ``key`` when set. Keeps
                # generated configs minimal and readable.
                if isinstance(writer, DebianChangelogWriter):
                    if writer.distribution != "UNRELEASED":
                        table["distribution"] = writer.distribution
                    if writer.urgency != "medium":
                        table["urgency"] = writer.urgency
                    if writer.debian_revision != 1:
                        table["debian_revision"] = writer.debian_revision
                    if writer.maintainer is not None:
                        table["maintainer"] = writer.maintainer
                    if writer.epoch is not None:
                        table["epoch"] = writer.epoch
                writers_array.append(table)
            section["writers"] = writers_array
        components_root.append(name, section)
    doc.append("components", components_root)

    return tomlkit.dumps(doc)


def _inline_filekey(fk: FileKey):
    inline = tomlkit.inline_table()
    inline["file"] = str(fk.file)
    if fk.key is not None:
        inline["key"] = fk.key
    return inline


def _filekey_array(items: list[FileKey]):
    array = tomlkit.array()
    array.multiline(True)
    for fk in items:
        array.append(_inline_filekey(fk))
    return array
